# Generated by Django 2.2.3 on 2019-08-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20190806_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
