# Generated by Django 2.2.4 on 2019-08-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20190807_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
