# Generated by Django 2.2.4 on 2019-08-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entries_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='toyname',
            field=models.CharField(max_length=100),
        ),
    ]
